Director.create(name: "Werner Herzog", country: "Germany", yob: 1942, bio: "Werner Herzog is a German film director, screenwriter, author, actor, and opera director. Herzog is a figure of the New German Cinema. His films often feature ambitious protagonists with impossible dreams, people with unique talents in obscure fields, or individuals who are in conflict with nature.")
Director.create(name: "Adam Curtis", country: "England", yob: 1955, bio: "Kevin Adam Curtis is a British documentary film-maker. Curtis says that his favourite theme is 'power and how it works in society', and his works explore areas of sociology, psychology, philosophy and political history. Curtis describes his work as journalism that happens to be expounded via the medium of film.")
Director.create(name: "Ken Burns", country: "America", yob: 1953, bio: "Kenneth Lauren Burns is an American filmmaker, known for his style of using archival footage and photographs in documentary films. His widely known documentary series include The Civil War, Baseball, Jazz, The War, The National Parks: America's Best Idea, Prohibition, The Roosevelts, and The Vietnam War.")

Movie.create(title: "The Civil War", director: Director.third, year: 1990, bio: "bio text here")
Movie.create(title: "The Vietnam War", director: Director.third, year: 2017, bio: "bio text here")
Movie.create(title: "The Century of the Self", director: Director.second, year: 2002, bio: "bio text here")
Movie.create(title: "Pandora's Box", director: Director.second, year: 1992, bio: "bio text here")
Movie.create(title: "Bitter Lake", director: Director.second, year: 2015, bio: "bio text here")
Movie.create(title: "HyperNormalisation", director: Director.second, year: 2016, bio: "bio text here")
Movie.create(title: "Cave of Forgotten Dreams", director: Director.first, year: 2010, bio: "bio text here")
Movie.create(title: "Fata Morgana", director: Director.first, year: 1971, bio: "bio text here")
Movie.create(title: "La Soufrière", director: Director.first, year: 1977, bio: "bio text here")

User.create(username: "bellajak", display_name: "movie_fan511", bio: "Big fan of MOOO00VIES:)")
User.create(username: "loginman", display_name: "forumguy", bio: "my favorite movie is documentaries hahaha")
User.create(username: "dochead", display_name: "dochead", bio: "just lookin for a good time, fellow docheads")
User.create(username: "movie_user", display_name: "binz", bio: "BINZ!")

Review.create(movie: Movie.all[0], user: User.first, rating: 90, content: "really big fan!")
Review.create(movie: Movie.all[1], user: User.third, rating: 85, content: "wow")
Review.create(movie: Movie.all[2], user: User.fifth, rating: 70, content: "man o man")
Review.create(movie: Movie.all[3], user: User.fourth, rating: 23, content: "what happened?")
Review.create(movie: Movie.all[4], user: User.second, rating: 55, content: "meh")
Review.create(movie: Movie.all[5], user: User.second, rating: 82, content: "cool stuff")
Review.create(movie: Movie.all[6], user: User.fourth, rating: 43, content: "blech")
Review.create(movie: Movie.all[7], user: User.fifth, rating: 51, content: "wowowowo")
Review.create(movie: Movie.all[8], user: User.third, rating: 93, content: "seriously. wow.")
Review.create(movie: Movie.all[0], user: User.first, rating: 84, content: "man!")
Review.create(movie: Movie.all[1], user: User.third, rating: 68, content: "uhhhh okay")
Review.create(movie: Movie.all[2], user: User.fifth, rating: 34, content: "this sucked so bad")
Review.create(movie: Movie.all[3], user: User.fourth, rating: 65, content: "heh")
Review.create(movie: Movie.all[4], user: User.second, rating: 42, content: "hehehehe")
Review.create(movie: Movie.all[5], user: User.second, rating: 91, content: "amazing")
Review.create(movie: Movie.all[6], user: User.fourth, rating: 14, content: "amazing...ly bad!")
Review.create(movie: Movie.all[7], user: User.fifth, rating: 65, content: "seen better")
Review.create(movie: Movie.all[8], user: User.first, rating: 10, content: "never seen worse.")